### ISSUE TITLE
warp fails to build on GHC 9.2

### ISSUE THREAD

**Issue by danwdart** [yesodweb/wai#861]
```
Network/Wai/Handler/Warp/ReadInt.hs:44:39: error:
    • Couldn't match expected type ‘Word#’ with actual type ‘Word8#’
    • In the first argument of ‘word2Int#’, namely
        ‘(indexWord8OffAddr# addr (word2Int# i))’
      In the first argument of ‘I#’, namely
        ‘(word2Int# (indexWord8OffAddr# addr (word2Int# i)))’
      In the expression:
        I# (word2Int# (indexWord8OffAddr# addr (word2Int# i)))
   |
44 | mhDigitToInt (W8# i) = I# (word2Int# (indexWord8OffAddr# addr (word2Int# i)))
   |

Network/Wai/Handler/Warp/ReadInt.hs:44:74: error:
    • Couldn't match expected type ‘Word#’ with actual type ‘Word8#’
    • In the first argument of ‘word2Int#’, namely ‘i’
      In the second argument of ‘indexWord8OffAddr#’, namely
        ‘(word2Int# i)’
      In the first argument of ‘word2Int#’, namely
        ‘(indexWord8OffAddr# addr (word2Int# i))’
   |
44 | mhDigitToInt (W8# i) = I# (word2Int# (indexWord8OffAddr# addr (word2Int# i)))
```

Using latest master on nix.

**Comment by danwdart** [comment]
A change in `ghc-prim` recently probably caused this.

Looks like if I change the offending line from:
```haskell
mhDigitToInt (W8# i) = I# (word2Int# (indexWord8OffAddr# addr (word2Int# i)))
```

to:
```haskell
mhDigitToInt (W8# i) = I# (int8ToInt# (word8ToInt8# (indexWord8OffAddr# addr (int8ToInt# (word8ToInt8# i)))))
```

it compiles and passes relevant tests.

Included a draft PR in https://github.com/yesodweb/wai/pull/862 as still not sure how this affects earlier versions of GHC.

**Comment by danwdart** [comment]
Also unsure how much performance is impacted by converting `Word8` to `Int8` and then `Int` or converting `Word8` to `Word` and then `Int`, or how the host/target bitness will affect things.

**Comment by fumieval** [comment]
#863 fixed this

**Comment by kazu-yamamoto** [comment]
Let's close.
