### ISSUE TITLE
wai-extra fails to build on Windows

### ISSUE THREAD

**Issue by tfausak** [yesodweb/wai#879]
I am not able to build wai-extra version 3.1.9 on Windows. I get a handful of errors when compiling `Network.Wai.Handler.CGI`:

```
[ 3 of 36] Compiling Network.Wai.Handler.CGI ( Network\Wai\Handler\CGI.hs, dist\build\Network\Wai\Handler\CGI.o )

Network\Wai\Handler\CGI.hs:58:35: error:
    Not in scope: ‘System.IO.stdin’
    No module named ‘System.IO’ is imported.
   |
58 |     let input = requestBodyHandle System.IO.stdin
   |                                   ^^^^^^^^^^^^^^^

Network\Wai\Handler\CGI.hs:59:25: error:
    Not in scope: ‘System.IO.stdout’
    No module named ‘System.IO’ is imported.
   |
59 |         output = B.hPut System.IO.stdout
   |                         ^^^^^^^^^^^^^^^^

Network\Wai\Handler\CGI.hs:69:35: error:
    Not in scope: ‘System.IO.stdin’
    No module named ‘System.IO’ is imported.
   |
69 |     let input = requestBodyHandle System.IO.stdin
   |                                   ^^^^^^^^^^^^^^^

Network\Wai\Handler\CGI.hs:70:25: error:
    Not in scope: ‘System.IO.stdout’
    No module named ‘System.IO’ is imported.
   |
70 |         output = B.hPut System.IO.stdout
   |                         ^^^^^^^^^^^^^^^^

Network\Wai\Handler\CGI.hs:183:22: error:
    Not in scope: type constructor or class ‘Handle’
    |
183 | requestBodyHandle :: Handle -> Int -> IO (IO B.ByteString)
    |                      ^^^^^^
Process completed with exit code 1.
```

I think this was introduced by #875. Specifically these lines of CPP don't seem to import `System.IO` properly on Windows:

https://github.com/yesodweb/wai/blob/5321b1a639a0fc0261387ea15cfac9de322e36db/wai-extra/Network/Wai/Handler/CGI.hs#L34-L43

**Comment by snoyberg** [comment]
CC @Vlix

**Comment by Vlix** [comment]
Ah, automatic linting threw the `System.IO` imports into the `else` :facepalm: Will fix in the PR (#880) that's standing right now.

**Comment by snoyberg** [comment]
@Vlix I implemented a smaller version of that fix, since that PR is pretty large and I don't want to block things.

@tfausak this should now be fixed with wai-extra 3.1.10.

**Comment by Vlix** [comment]
👍 No prob

**Comment by tfausak** [comment]
Thanks! I can confirm that #881 and version 3.1.10 fixed my problem. Perhaps deprecating version 3.1.9 might be in order?

**Comment by snoyberg** [comment]
Good idea, deprecated on Hackage.
