### ISSUE TITLE
warp 3.3.5 does not build with base 4.16

### ISSUE THREAD

**Issue by chris-martin** [yesodweb/wai#867]
Warp could use a metadata revision to indicate that 3.3.5 (I assume other versions as well) does not build with base 4.16.

```
Network/Wai/Handler/Warp/ReadInt.hs:44:39: error:
Error:     • Couldn't match expected type ‘Word#’ with actual type ‘Word8#’
    • In the first argument of ‘word2Int#’, namely
        ‘(indexWord8OffAddr# addr (word2Int# i))’
      In the first argument of ‘I#’, namely
        ‘(word2Int# (indexWord8OffAddr# addr (word2Int# i)))’
      In the expression:
        I# (word2Int# (indexWord8OffAddr# addr (word2Int# i)))
   |
44 | mhDigitToInt (W8# i) = I# (word2Int# (indexWord8OffAddr# addr (word2Int# i)))
   |                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Network/Wai/Handler/Warp/ReadInt.hs:44:74: error:
Error:     • Couldn't match expected type ‘Word#’ with actual type ‘Word8#’
    • In the first argument of ‘word2Int#’, namely ‘i’
      In the second argument of ‘indexWord8OffAddr#’, namely
        ‘(word2Int# i)’
      In the first argument of ‘word2Int#’, namely
        ‘(indexWord8OffAddr# addr (word2Int# i))’
   |
44 | mhDigitToInt (W8# i) = I# (word2Int# (indexWord8OffAddr# addr (word2Int# i)))
   |                                                                          ^
```

**Comment by polyrod** [comment]
Had the same issue : workaround

add the snippet from : http://head.hackage.haskell.org/

to your .cabal or better cabal.project file

cabal update && cabal clean && cabal build

will do then

**Comment by kazu-yamamoto** [comment]
This issue has been fixed in the newer versions.

**Comment by chris-martin** [comment]
Thank you, I appreciate that there are newer versions that support base 4.16. What I'm suggesting is that the bounds for the older versions could be corrected. Having accurate bounds information across all the releases helps users find collections of versions that will work together without having to just experiment with compiling various configurations to find out what will build.

**Comment by chris-martin** [comment]
I understand if it is not worth taking the time to support older minor releases. In that case, I think an equally helpful course of action would be to deprecate them.

**Comment by kazu-yamamoto** [comment]
There are a lot of old versions. Only v3.3.18 can be built with GHC 9.x.
Are you suggesting that we should modify all version except v3.3.18 with `< 4.16` or deprecate them?
It's a very tough job, I guess.

**Comment by chris-martin** [comment]
In the 3.3 series, there are 18 previous releases to be corrected. If we already know for sure that nothing prior to 3.3.18 supports base 4.16, then it takes maybe 30 seconds to change each one via the Hackage web interface, so I reckon that's about nine minutes of labor. Happy to help if I can.

**Comment by kazu-yamamoto** [comment]
I remember that metadata on hackage can be modified by a command-line tool. But I cannot recall its name. Do you know that?

**Comment by kazu-yamamoto** [comment]
`hackage-cli`!

**Comment by kazu-yamamoto** [comment]
`hackage-cli` cannot be build with GHC 8.6 on Monterey, sigh.

**Comment by chris-martin** [comment]
Bounds for warp-3.3.0 to warp-3.3.5 have been corrected by hackage trustees. https://github.com/haskell-infra/hackage-trustees/issues/329
