### ISSUE TITLE
warp 3.3.6 broke warp-tls-3.2.9 (the latest version to support GHC 8.0)

### ISSUE THREAD

**Issue by int-e** [yesodweb/wai#798]
This comes rather late, but because https://github.com/yesodweb/wai/commit/f8282948d891fbf6a9e6dc22ca1339b4a5275817 added a new (strict) field to the `TLS` constructor of the `Transport` type, warp 3.3.6 was not API-compatible with 3.3.5.

As a result, trying to install warp-tls with cabal-install on GHC 8.0.2 currently finds no viable installation plan: it picks up warp-tls-3.2.9, and warp-3.3.9 as a dependency. But then the build fails like this:

```
$ cabal install warp-tls
[...]
Building library for warp-tls-3.2.9..
[1 of 1] Compiling Network.Wai.Handler.WarpTLS ( Network/Wai/Handler/WarpTLS.hs, dist/dist-sandbox-aa7fbab9/build/Network/Wai/Handler/WarpTLS.dyn_o )

Network/Wai/Handler/WarpTLS.hs:471:20: error:
    • Constructor ‘TLS’ does not have the required strict field(s): tlsClientCertificate
```

There are two easy fixes for Hackage users:
- add an upper bound `warp < 3.3.6` for [warp-tls 3.2.9](https://hackage.haskell.org/package/warp-tls-3.2.9) on Hackage (using the revision mechanism)
- relax the lower bound on `base` of [warp-tls 3.2.11](https://hackage.haskell.org/package/warp-tls-3.2.11) to 4.9. (See https://github.com/yesodweb/wai/commit/9141e27fc46bd8ec1333acec0dd0d04f52c2b137 which "dropped GHC 7.10 support", but also excluded base-4.9 that GHC 8.0 ships. I've checked that warp-tls currently builds with base-4.9, if allowed.)

Given that GHC 8.0 is getting old, the first fix seems appropriate to me. And it should be quick enough to not be a burden. :-)

**Comment by kazu-yamamoto** [comment]
@int-e Thank you for reporting. I did the first option. Would you confirm?

**Comment by int-e** [comment]
Looks good to me, thanks! (closing)
